/*
 * This source file was generated by the Gradle 'init' task
 */
package pbo;

public class App {

    public void start() {
        System.out.println("Template");
    }

    public static void main(String[] args) {
        new App().start();
    }
}
